from CipherUtils import *

print("3A")
text = """
FTNPTQP RDF TGOBTLFKX HPPQ IYDI B FYTLKM HQTR DGTLI MTLVKDF GKDJH GLI B RDF KPSI RTQMPCBQV RYDI YP YDM IT MT RBIY IYP FYDMTR DCJYBOP. B STLQM FTNP ICDJPF TS YBN BQ GTFITQ QPRFWDWPC JKBWWBQVF SCTN IYP WPCBTM. IYP FITCBPF FITWWPM BQ 1873, DCTLQM IYP MDIP TS IYP KPIIPCF GPIRPPQ OBJITCBD DQM FBC JYDCKPF, FT B DFFLNP YP CPILCQPM IT PQVKDQM IYPQ, GLI B JTLKMQ’I SBQM DQX CPJTCM TS YBN BQ IYP BNNBVCDIBTQ SBKPF DQM IYPCP RDF QTIYBQV BQ IYP TSSBJBDK CPJTCM IT FLVVPFI IYDI YP NPI RBIY FBC JYDCKPF, KPI DKTQP RBIY YPC NDEPFIX. IYP ICDBK YDM VTQP JTKM DQM B NBVYI YDOP NTOPM TQ DI IYDI WTBQI, GLI IYPQ B VTI IYP IYBCM PNDBK. IYBF IBNP BI RDF D HPXRTCM JBWYPC DQM BI ITTH D KBIIKP KTQVPC IT GCPDH, IYTLVY IYP RTCM FICLJILCP YPKWPM D KTI. BI JTQSBCNPM POPCXIYBQV B YDM VLPFFPM FT SDC DGTLI GKDJH, DQM CDBFPM D RYTKP KTDM TS QPR ZLPFIBTQF! BI DKFT FLVVPFIPM IYDI B NBVYI SBQM DQFRPCF BQ IYP FYDMTR DCJYBOP, GLI SBCFI B YDM IT SBVLCP TLI RYPCP BI RDF, DQM YTR B JTLKM VPI BQ. B FIBKK JDQ’I GPKBPOP BI, GLI IYP DQFRPC JDNP SCTN D VTTVKP FPDCJY. B RDF KTTHBQV STC D KTJDIBTQ IYDI RTLKM YDOP WCTOBMPM GKDJH RBIY JTOPC STC D FICPDN TS OBFBITCF, WCPSPCDGKX BQ D JPQICDK KTQMTQ KTJDIBTQ, DQM RBIY SDJBKBIBPF STC FPJLCP FITCDVP TS TSSBJBDK CPJTCMF, DQM BI FYTLKM YDOP GPPQ TWPQPM BQ 1873 TC 1874. B FPDCJYPM STC “GKDJH, KTQMTQ, 1874” DQM B KBHPM RYDI B STLQM. DQM IYDI BF RYX B STLQM NXFPKS KXBQV TQ IYP CTTS TS IYP QTCNDQ FYDR GLBKMBQVF BQ IYP NBMMKP TS IYP QBVYI DQM BQ WTLCBQV CDBQ! B YDM IT SBVLCP TLI D RDX TS VPIIBQV BQFBMP TQP TS IYP NTFI FPJLCP KTJDIBTQF BQ PQVKDQM!
"""
Utils.get_stats(text)
plain = Affine.auto_decode(text)
print("Affine Shift %d, %d: %s" % (plain[0][0], plain[0][1], plain[1]))


"""
Affine Shift, 3, 3: SOMEONE WAS OBVIOUSLY KEEN THAT I SHOULD KNOW ABOUT DOUGLAS BLACK BUT I WAS LEFT WONDERING WHAT HE HAD TO DO WITH THE SHADOW ARCHIVE. I FOUND SOME TRACES OF HIM IN BOSTON NEWSPAPER CLIPPINGS FROM THE PERIOD. THE STORIES STOPPED IN 1873, AROUND THE DATE OF THE LETTERS BETWEEN VICTORIA AND SIR CHARLES, SO I ASSUME HE RETURNED TO ENGLAND THEN, BUT I COULDN’T FIND ANY RECORD OF HIM IN THE IMMIGRATION FILES AND THERE WAS NOTHING IN THE OFFICIAL RECORD TO SUGGEST THAT HE MET WITH SIR CHARLES, LET ALONE WITH HER MAJESTY. THE TRAIL HAD GONE COLD AND I MIGHT HAVE MOVED ON AT THAT POINT, BUT THEN I GOT THE THIRD EMAIL. THIS TIME IT WAS A KEYWORD CIPHER AND IT TOOK A LITTLE LONGER TO BREAK, THOUGH THE WORD STRUCTURE HELPED A LOT. IT CONFIRMED EVERYTHING I HAD GUESSED SO FAR ABOUT BLACK, AND RAISED A WHOLE LOAD OF NEW QUESTIONS! IT ALSO SUGGESTED THAT I MIGHT FIND ANSWERS IN THE SHADOW ARCHIVE, BUT FIRST I HAD TO FIGURE OUT WHERE IT WAS, AND HOW I COULD GET IN. I STILL CAN’T BELIEVE IT, BUT THE ANSWER CAME FROM A GOOGLE SEARCH. I WAS LOOKING FOR A LOCATION THAT WOULD HAVE PROVIDED BLACK WITH COVER FOR A STREAM OF VISITORS, PREFERABLY IN A CENTRAL LONDON LOCATION, AND WITH FACILITIES FOR SECURE STORAGE OF OFFICIAL RECORDS, AND IT SHOULD HAVE BEEN OPENED IN 1873 OR 1874. I SEARCHED FOR “BLACK, LONDON, 1874” AND I LIKED WHAT I FOUND. AND THAT IS WHY I FOUND MYSELF LYING ON THE ROOF OF THE NORMAN SHAW BUILDINGS IN THE MIDDLE OF THE NIGHT AND IN POURING RAIN! I HAD TO FIGURE OUT A WAY OF GETTING INSIDE ONE OF THE MOST SECURE LOCATIONS IN ENGLAND!
"""


print("3B")
text = """
CTN HLETPQW DP NDBCQ, GDZT DI OJPQJI DP ARGG, ORQ IJQ ARGG TIJRBC QJ KTNPRLAT HT QCLQ UJNFDIB ZJN CTN UJRGA OT UJNQC QCT NDPF. ORQ JZ YJRNPT PCT CLA LI LIPUTN ZJN QCLQ. PCT KJDIQTA JRQ QCLQ NTQRNIDIB QJ QCT RIDQTA PQLQTP YLNNDTA DQP JUI NDPFP.

D CLA FTKQ HWPTGZ LHRPTA ZJN QCT GLPQ ZTU WTLNP PTKLNLQDIB QCT BNTTAW LIA STILG ZNJH QCTDN HJITW OW L SLNDTQW JZ HTLIP, IJQ LGG JZ QCTH TIQDNTGW LKKNJSTA OW QCT GLU. D ULP GTZQ UJIATNDIB CJU QCT MRTTI FITU LOJRQ QCLQ, LIA UCTQCTN HW YJRPDI CLA OTTI DIPQNRYQTA QJ QTGG QCT ZTATNLG HLNPCLGGP LOJRQ HW LYQDSDQDTP. ADPYNTQDJI PTTHTA QCT UDPT YJRNPT, LIA LIWULW, CJU JZQTI AJ WJR BTQ L EJO JZZTN ZNJH L MRTTI?

YCLNGTP CLP AJIT L PQTNGDIB EJO ATSTGJKDIB L ITQUJNF JZ LBTIQP LIA CDP DIQTGGDBTIYT JKTNLQDJIP CLST OTYJHT L FTW KLNQ JZ ONDQDPC ADKGJHLYW. QCT BNJUDIB DIPQLODGDQW LYNJPP TRNJKT QCNTLQTIP QCT THKDNT, LIA DQ DP CTN HLETPQW’P OTGDTZ QCLQ UT UDGG ITTA QJ NTPKJIA DI FDIA QJ ATPQLODGDPT JRN TITHDTP OTZJNT QCTW BNJU QJJ PQNJIB. QCDP DP L ITU LIA ALIBTNJRP FDIA JZ ULNZLNT, ORQ YJRGA, D PRKKJPT, PLST GDSTP, LIA UT UDGG, DI LIW YLPT, ITTA QJ HLQYC JRN TITHDTP DZ UT LNT QJ PQLW LCTLA.

QCDP TIQDNT JKTNLQDJI HRPQ OT FTKQ PTYNTQ. ZDNPQ ZNJH JRN TITHDTP, ORQ PTYJIA, LIA ERPQ LP DHKJNQLIQ, ZNJH QCT JZZDYDLG HLYCDITNW JZ PQLQT. CTN HLETPQW YLIIJQ LZZJNA QCT NDPF QCLQ CTN BJSTNIHTIQ YJRGA OT DHKGDYLQTA DI QCTPT JKTNLQDJIP, LIA PDN YCLNGTP CLP NTLPJI QJ OTGDTST QCLQ QCT ZJNTDBI JZZDYT HLW CLST OTTI YJHKNJHDPTA. ZJN QCDP NTLPJI UT ITTA QJ HJST PDN YCLNGTP’ DIQTGGDBTIYT JKTNLQDJI QJ L HJNT PTYRNT GJYLQDJI. LIA D QCDIF D CLST LI DATL UCTNT QCLQ YJRGA OT!

"""
Utils.get_stats(text)
print(Keyword.decode(text, 'loyatz'))


"""
Keyword Substitution Cipher: LOYATZ
HER MAJESTY IS RIGHT, LIFE IN BOSTON IS DULL, BUT NOT DULL ENOUGH TO PERSUADE ME THAT WORKING FOR HER WOULD BE WORTH THE RISK. BUT OF COURSE SHE HAD AN ANSWER FOR THAT. SHE POINTED OUT THAT RETURNING TO THE UNITED STATES CARRIED ITS OWN RISKS.

I HAD KEPT MYSELF AMUSED FOR THE LAST FEW YEARS SEPARATING THE GREEDY AND VENAL FROM THEIR MONEY BY A VARIETY OF MEANS, NOT ALL OF THEM ENTIRELY APPROVED BY THE LAW. I WAS LEFT WONDERING HOW THE QUEEN KNEW ABOUT THAT, AND WHETHER MY COUSIN HAD BEEN INSTRUCTED TO TELL THE FEDERAL MARSHALLS ABOUT MY ACTIVITIES. DISCRETION SEEMED THE WISE COURSE, AND ANYWAY, HOW OFTEN DO YOU GET A JOB OFFER FROM A QUEEN?

CHARLES HAS DONE A STERLING JOB DEVELOPING A NETWORK OF AGENTS AND HIS INTELLIGENCE OPERATIONS HAVE BECOME A KEY PART OF BRITISH DIPLOMACY. THE GROWING INSTABILITY ACROSS EUROPE THREATENS THE EMPIRE, AND IT IS HER MAJESTY’S BELIEF THAT WE WILL NEED TO RESPOND IN KIND TO DESTABILISE OUR ENEMIES BEFORE THEY GROW TOO STRONG. THIS IS A NEW AND DANGEROUS KIND OF WARFARE, BUT COULD, I SUPPOSE, SAVE LIVES, AND WE WILL, IN ANY CASE, NEED TO MATCH OUR ENEMIES IF WE ARE TO STAY AHEAD.

THIS ENTIRE OPERATION MUST BE KEPT SECRET. FIRST FROM OUR ENEMIES, BUT SECOND, AND JUST AS IMPORTANT, FROM THE OFFICIAL MACHINERY OF STATE. HER MAJESTY CANNOT AFFORD THE RISK THAT HER GOVERNMENT COULD BE IMPLICATED IN THESE OPERATIONS, AND SIR CHARLES HAS REASON TO BELIEVE THAT THE FOREIGN OFFICE MAY HAVE BEEN COMPROMISED. FOR THIS REASON WE NEED TO MOVE SIR CHARLES’ INTELLIGENCE OPERATION TO A MORE SECURE LOCATION. AND I THINK I HAVE AN IDEA WHERE THAT COULD BE!
"""

