from CipherUtils import *

print("Challenge 7")
print("Part A")

text = """
EODNJ XPMTD JBHMT BTDGT UJYEU MDIZJ IKHEA KJAPJ TEJUY EUNDY EDHBK ZGJTE PTDGX BZSSB ZEURP BKMUX XEONK IEJTE CKZUJ MDIDC HBREI IUBZD XTUJV KIJJT EHUST JDYBK ZJBRR BHNEJ BWZBN WYEBK JCHBA DAXPZ BCEHY DZEZJ GDYDS EJTEH BBYTD GAEEZ EOCEH JXPGU IDIIE YAXEG JTEIT EXLEI MEHEE YCJUE GBRAX DNWIY UIIUB ZRUXE IDZGY KNTBR JTEIJ EDYCK ZWJEN TZBXB SPTDG AEEZJ DWEZD CDHJC HEIKY DAXPJ BYDWE IKHEU JGUGZ JNBZJ DUZDZ PRKHJ TEHIE NHEJI JTEAU SAEDK JURKX HBKZG JDAXE TDGAE EZNXE DHEGD ZGUXE DZJBZ UJJBI JEDGP YPIEX RDIYP TEDGI MDYUS KEIIE GJTDJ MTBEL EHTDG RBXXB MEGYE UZJBJ TEJKZ ZEXID ZGBZU ZJBJT ETEDG FKDHJ EHIYK IJTDL EWZBM ZMTDJ UMDIX BBWUZ SRBHU JMDIJ BBYKN TBRDN BUZNU GEZNE JTDJJ TEPTD GRBKZ GYETE HECHB ADAXP JTEPM EHENB ZZENJ EGMUJ TJTEE YDUXI JTDJR UHIJS BJYEU ZJEHE IJEGU ZAXDN WAKJU ZDNBZ RKIEG IJDJE DRJEH YPAXD NWBKJ UMDIC KQQXE GMTPT DGJTE PUZLB XLEGY ECEHT DCIJT EPVKI JGUGZ JWZBM TBMJB RUZGJ TEITD GBMDH NTULE DZGTB CEGUM BKXGA EDAXE JBTEX CCEHT DCIJT EPMDZ JEGJB UYCXU NDJEY EUZJT EJTER JBRJT EITDG BMDHN TULEC DCEHI UZJTD JNDIE JTEPI TBKXG TDLET UJYET DHGEH UMDIZ JSBUZ SJBTD ZSDHB KZGXB ZSEZB KSTJB SEJND KSTJI BYEJT UZSMD IZDSS UZSDJ YEZBZ EBRJT ECDCE HIUTD GIEEZ XBBWE GUZJE HEIJU ZSEZB KSTJB VKIJU RPDXX JTUIE RRBHJ UJKHZ EGYPT EDGND KJUBK IXPJH PUZSJ BUSZB HEJTE JTHBA AUZSA ETUZG YPEDH DZGXB BWEGD HBKZG JTEHB BYBZE YBHEJ UYEJB IEEMT DJMEM EHEYU IIUZS DIUGU GIBYP RBBJN DKSTJ BZIBY EJTUZ SDZGU AEZJG BMZJB CUNWU JKCMT EZJTE PTUJY EUTDG AEEZI UJJUZ SHEDG UZSAX DNWIN BGEAB BWUJM DIRKX XBRYD HLEXX BKIUR GDJEG UGEDI BZNHP CJBSH DCTPD ZGUZR BHYDJ UBZIE NKHUJ PDZGU TDGVK IJAEE ZHEDG UZSJT EIENJ UBZBZ JHDZI CBIUJ UBZNU CTEHI UJIEE YEGTE MDICD HJUNK XDHXP WEEZB ZNBXK YZDHJ HDZIC BIUJU BZIDZ GMDID HSKUZ SJTDJ UJMBK XGAEA EIJJB HEDGB RRJTE NUCTE HJEOJ NBXKY ZAPNB XKYZJ BNBZR KIEEZ EYPNH PCJDZ DXPIJ IUMDI YKIUZ SBZVK IJTBM IENKH EJTDJ MBKXG AEMTE ZJTEM BHXGM EZJGD HWXKN WUXPD IUTDG RDXXE ZUTDG GHBCC EGJTE ABBWD ZGUJT DGIXU CCEGK ZGEHJ TEJDA XEIBY ETBMJ TEPTD GYUII EGUJG KHUZS JTEIE DHNTD ZGJTE HEUJM DITUG GEZUZ JTEIT DGBMI UJBBW DGEEC AHEDJ TJBIX BMJTE ICUZZ UZSAE TUZGY PEPEI DZGCU NWEGJ TEABB WKCAK JDIUC KXXEG YPIEX RKCHU STJDS DUZJT EJDAX EJBCI TURJE GIXUS TJXPJ BBZEI UGEUI JHKSS XEGJB HESDU ZYPAD XDZNE DZGJT EJDAX EYBLE GDSDU ZDZGJ TUIJU YEUTE DHGDG UIJUZ NJNXU NWDIU ITURJ EGYPM EUSTJ JTEJD AXEHB JDJEG ADNWD ZGJTE HEUJM DIBZN EYBHE DIBRJ YEJDX XUNNX UZWDI DHDJN TEJJB BJTEZ SDSEG UIJBB GKCSH DAAEG DJJTE JDAXE DZGCK XXEGI UGEMD PIUJJ KHZEG DSDUZ NXUNW UZSIE LEHDX JUYEI DIUJG UGIBU JMDID ZBUIE UWZEM LEHPM EXXJT EJKYA XEHIB ZDIDR EYDGE JTEID YEIBK ZGJTB KSTYK NTYKN TFKUE JEH
""".replace(" ", "").strip()
Utils.get_stats(text)
key, plain = Substitution.auto_decode(text)
print(Substitution.key_as_str(key), plain)

"""
Substitution Cipher: DANGERSTUVWXYZBCFHIJKLMOPQ (Run-On Keyword: DANGER)
exactly what or who had hit me i wasnt sure but by the time i came around they had long gone if you will excuse the pun it was a professional hit just the right amount of force to knock me out probably no permanent damage the room had been expertly disassembled the shelves were emptied of blacks mission files and much of the steam punk technology had been taken apart presumably to make sure it didnt contain any further secrets the big beautiful roundtable had been cleared and i leant on it to steady myself as my head swam i guessed that whoever had followed me into the tunnels and on into the headquarters must have known what i was looking for it was too much of a coincidence that they had found me here probably they were connected with the emails that first got me interested in black but in a confused state after my blackout i was puzzled why had they involved me perhaps they just didnt know how to find the shadow archive and hoped i would be able to help perhaps they wanted to implicate me in the theft of the shadow archive papers in that case they should have hit me harder i wasnt going to hang around long enough to get caught something was nagging at men one of the papers i had seen looked interesting enough to justify all this effort i turned my head cautiously trying to ignore the throbbing behind my ear and looked around the room one more time to see what we were missing as i did so my foot caught on something and i bent down to pick it up when they hit me i had been sitting reading blacks code book it was full of marvellous if dated ideas on cryptography and information security and i had just been reading the section on transposition ciphers it seemed he was particularly keen on columnar transpositions and was arguing that it would be best to read off the cipher text column by column to confuse enemy cryptanalysts i was musing on just how secure that would be when the world went dark luckily as i had fallen i had dropped the book and it had slipped under the table somehow they had missed it during these arch and there it was hidden in the shadows i took a deep breath to slow the spinning behind my eyes and picked the book up but as i pulled myself upright again the table top shifted slightly to one side i struggled to regain my balance and the table moved again and this time i heard a distinct click as i shifted my weight the table rotated back and there it was once more a soft metallic clink as a ratchet tooth engaged i stood up grabbed at the table and pulled sideways it turned again clicking several times as it did so it was a noise i knew very well the tumblers on a safe made the same sound though much much quieter
"""

print("\nPart B")
text = """
HCOOT HEAOT DHEYM AAUHA MARRA RWBEH WNDNE ESEER ETNTI RWHAT NRTRY FMRSO VEHSB RNAUT SELTE GOUEG SDENH HEYDE SEERI OEUAI SHVLS RDAEO MACDN IFDNE IAEAS EANFO AHEEA ELNFM SREHI KHABT ICLIT CTFPV ETEII AHSIS PODIS GLLSI TOIIA DHLVA OTTGE OIIHT OGEES NGURF ISRRT TUUNB ANECS DAETS SGICE LTERV MHCIE ITCAO HIOTC ESTMO TWLPT AWRAN EINWC ELUON INISS SNHFH LSTDN CSTAJ AODHE AAOTE FEADT TSEWS PESAA HHMDO OEOET EETSF HORAI OLNYO EITUI EESSA UACET NAEER EVECT IEYNO HEOEH ECHEI SEEEI NAHAU EOUAF EORSO NNNEC UMFRS IRNSI UEOIE RTUCI REIAZ IOINP FRTTE FEPHI OENCS TLTET TCHWE RCLIF DTTTT ATLUB WTLLH ESRUE MNWAN ISOFM RSOFC CIARL SSTSR DCIIR NTWEE ONETP FIEEE ISNRE GNELI IECNN ENGUE RGNIN CTNEN EDEVL CEGTS CIIAN TAIOW OTMFO EHNTA SOEOR ITURA ILTDI HURMR ACUAE ALLSE GRSGU ENAEE ITTAO TTUMT OLLRA EGDTI TSRET RASCL NOEEC DIFDC MWCEA GPAAS TSTGO ATAHA FDRTE EYEBH DMWID NAAGU STRRI EAABO NEAGO OTEIE IEOSA NANRA ROLII NRETT ELEHE TNADI CANTO DOIUO NMGIO SYEIS ANIRF MSMEH CEOSH CRHRH AERRG GWTEA TTLEO NETDE NSEFH SHMRH LIHOE TESIN DEUHG TNLHT SFOGT SRNRC TWTTV RMHSO NTEOG DUARA AOORI IPUNN NHESD ARCHL SHPIE TANTR INLST LHSIV ISORO STOYM OASAT LEINT EFCOD ITAIA ATSST NANIU NNSAI FOSMR SPRDS ECNOO OLODO TUEET TENIY TIRSV RONTL ETTMP ANTHA IODCD EUDHE AIAED SWIVE TEFTE LEFTH GGTSE TTDDT HRNAY COSDP ETORC EOFOO EEOSA OEITU TRTRH SMWED CSNTN NIRNC HAISE SIRNH ITAOH GEEFA IREYI TOVOA EEOER EFASS ISTNA BFTBN POROI EMARI NOREI TRTSN LAWII IEOEN MMUER EHHCO CSOLF MVVTI OEHEA HNLWU EOORU LRHFN OLIXA AOIHE WABAH ANUNG RLONI VCTRA IIRBC RACAT MEPTD PUSML NNPTF PGONU RCGTI UAROA SAORD RCMMS IEHNE OOSNI LERHF NEROI EHFIO IDPIF RHTEN STEIT GETHI OLGAS GSERI SGHEO AGDIE LGNTR EGTNE ERROT NAUMW TPYWG TRDKT EPSDD HDEWG MEONP LTAHA INDID ETTHU EHESN GAABN GWFTA ORTCA DSRLS AEOFN NEDTT KERSR OTUTT HOENE ODMME ILHTE DANTI THOFE TEETL NTLHC MSDIN VRNNR ALTHI NEEYA OIENN ERSNU NTUCI UVEER BLOEF MIERE ODEAI TSUEG AUTIE SMSEI IRSOB IAEGF TNGEH EOOGR AHUOR PNMAL DSOAV GRIAS ADDTM FKEAE HAARI ITMLS TIERI EOAEH EANWT GLOEA HRROL EATEN TUTOH AONLH SESMH ATTFB NNCET RNOYD VHEEE STITT ROERE POOTN AIETS UEEAT OISSR SNETL SGGTH NDCIV RTRCN PMCSA ENTTR ESVES NRSNO NEELE IDTNN ELOTC NFNTI CKOTP GRBFF DICMT RKEUE OERIW EAIEA NEIOO TEROI RYPNF TETSE EUIOP WODTB HFSAT IOUET TTHCN NNLEI LONDI CTRNT OAYGH ITSSU NTOII ETEHI TEFEN HADEE ERONR AIESL ECURA NPOUU IEEEI KNANI OEEIE OORNS NFOMT IAEAO EUNBI KTENO NRIUD NCIHR RANWA HTTOA LNNTT EOPNN NMNFO TAHAU AWEDN REIRH PRWTN SLFSU NCLWH ANVRE REROH NNIDN EUFNI POESC ELTIS DNASR ESNNT EMEIR VNADO BPWSD OEEIR SOTNR SHSON IXNAE ANSSL OAOHA UPAIR NFOAE HLEAA HEEAT DCYST FHIHP NILRR ITEUE RAORS TTOJD MTTAI SCTEO USCAE TIIOG AEGNI CHAEF MFIAL ORIOR NCSNF OCROS LFROO GDALH ETSMG URENW SSWEI ONRWS ETTMS RRNNI WESTV TFEON TBTUE OOLAN ECREN ESEIM NHSNI LWDTT RGTAR SOLID NHENK FRTTW TLOSN FOPHC HGTAH ECBOA ORMT
""".replace(" ", "").strip()
Utils.get_stats(text)

l = 7
l2 = ceil(len(text)/l)
columns = [text[i:i+l2] for i in range(0, len(text), l2)]

rows = []
for i in range(len(columns[0])):
    try:  rows.append(''.join(columns[j][i] for j in range(l)))
    except IndexError: pass

print(ColumnarTransposition.auto_decode(''.join(rows), l, l))

"""
Transposition Cipher (Reading rows): (1, 6, 4, 2, 0, 5, 3)
the chaos and confusion that followed the reichstadt meeting was more complete than i had any right to hope the playfair gambit was an outstanding success the delegates from russia and austrohungary each had a clear view of what had been agreed and these views were entirely divergent even better the records of the meeting were entirely independent of one another at the urging of our agents within the separate courts the minutes were dictated separately by the two foreign ministers andrassy and gorchakov so as to ensure the deepest possible understanding of the agreed outcomes there was no signed formal convention nor even an agreed protocol our subtle campaign of whispers and misdirection ensured that neither side entirely trusted the other so these minutes were never shared the discussions concerning austrian annexation in bosnia and herzegovenia will confuse historians and diplomats for generations to come it has already confused the principals in this affair and no one in the foreign office can make sense of them at all despite the great care taken by the officers of the shadow archive to record them accurately there is talk of the need for further meetings of the great powers and this time i will make sure that britain will beat the table to influence the deliberations and to protect our interests from the point of view of her majesty and the prime minister if not that of all her ministers this is close to the perfect outcome discussion is displacing war and low level distrust is inhibiting the sort of organised alliance that might diminish our influence over the gateway to the east the forthcoming conference in constantinople will for the first time involve our government in the discussions concerning the future governance of the region lord salisbury will argue for the creation of autonomous regions under bulgarian rule in the hope of reducing tensions and eliminating the excuse that russia needs to engage in war if he succeeds then we will have established a comprehensive agreement with russia concerning its territorial ambitions in central asia resolving the conflict with our own strategic aims even if this proves to be too much for our negotiators we can at least hope to buy time to make our own preparations and to manipulate our allies and enemies i will concentrate on developing further confusion spreading misinformation and as much distrust as i can manage if the talks fail we should at least ensure that no grand bargain is struck against our interests and no major alliance is formed to diminish us the mediterranean is a choke point for the trade routes from the east we cannot and will not allow others to strangle the flow of goods and people that enrich us no threat is greater to the health of the empire and no action is beyond contemplation in our efforts to remove the threat
"""