from CipherUtils import *

text = """
kdIgb oimce idkot seeii huotn pteho mmswi heeoa taoue taebw niInc fnkll flnho unwtd mamtg maera ieanw ronko tsstn kemta rahdn heIpo nsiac oiaeh lntai lbhsh oesoh lhtka rttts aehhI vldTh tunau ehshe noceI aireh rvsrw thett tuaea eseid eeeem topeh eohfB eoodn pafto enect dvasi bpsti xtrrp hfost wiekh Idnpb chrls fidoa atwit urgsd nedao hhgsh iaoeo ricot sgnrg ktedr hanoh tsmao Tehtf morsi ngkhe phtat bmrtt ooeap ctdJt marcs eedad bnier nrhhm rkshg eodBf emahf oeocr ctdfc tvMsy rlneu ooklu nobks nnhhe snosd naenu ueknh noydd Isiwl hseei uibby hatdo ybaeo pAntT sftek atpwa neuoo plttt abtte etioh mrhuh cfsto aeaip otiVc olsgI asstt atyla oodsu ebple rlecs acles hsham ierth ocoen etatn eluhn ehtnw auaih eerje hsaea kshtw cslrh eohin euteI ldelo trele aiutm mesrr oleet setwi naerw aouhe aiawy dycsu tltgu eecni atdte whiks ldlre uoaeg iivsn noleI atorn uscen heuaa tcplr dwato Imath eengb rafal bhade phdgh tgees eniat chdsa dmept oiiku ceuii ereyd ttsun cetTs oieeg naetn sligi tepod legtI oiors rhaaf hgpuc doite tdplh nlell irhpo Scrie eerTo wahto roesi efedu eoanb ahwae Vnnkt oueaS cober seeht rseha rtsda ntmia ahute ebhmI lbnot eyatt ndnht uHoht leade osytl ylwut uoIoa cwmll eints eIoeu retlu ekycb Iuime fnhmi orehv piafe ostto rnhoi lsnne alacn fndof eIhhi cttrh hhltf teipd rTnes ethtp bwenr rpksr mmein tiioa loamr achti deeuw lanse pohhi lidtk achce ynaoh oswum tlond eelaa dmiLd hhrii rhhue tettv eycet aceeo syIhr tcdan orcuo iwvlt wtror Ibdbt ebgal iulrt bduns nswva talsn gfois dytvd tadlk lniwh etcsi kasle yrtda inmen eeacd nluIa hotga ityet erbyt crebc hsead nuIop nolwy daoek iceuw iauan otdaa efood ddhnh octle itehd rfbls adfeo cemla kMkeh Aaiai tmhet udren tiate tuacy adsso eHlai inald oahhA tluwe errre iysta aihko lhymh lelos strmi rnadt asbde dpwdn ennet ttuol wlhni vtoew tidtn ceoeo cfhno rtorh errdt oepmc ceacl heeil eeagn wydnm heaew dnece hngpe tietw wumnp oanee ihitt gsalt hgrhc evett anaaa rtrnl sdenc uagcc dktdo uloyt aucth otnse eaard tdvdr siafn smuey hceha asnke oeett acitn ktnfd nidto dvdee eaone fifim elahr ohnao iweii aatgd sldeI iweuo sncle etrea eaaea oarrt csdal nweet lehwr xeaue eefno ggatt idctt kinet htuss hnctt netot eoanc wrhts rutee ooanh oeehe dlnny tdwed feapw cpdet hnmab ngtyr atnbc anmpl feiet hhdtn obeio asmmn uotio rapre yider rmtbh anlhf timtl klhHa rnobs motfc eefna actfb feerc ysetr ktiAt bwtsf fawod ewyed nyvmm teela idnhn eunae Utnot vtnic hlwpa laato Ilrot stsdk aurrh ianre oroef sepho loyko ltkei rytoi mtoth hIgei rtboi tttre oehde n
""".replace(" ", "").strip()

Utils.get_stats(text)
t = ColumnarTransposition.alternate_decode(text, (2, 5, 7, 3, 4, 0, 6, 1))
print(t)
# print(Utils.insert_spaces(t))

"""
Transposition Cipher (Reading Rows): (2, 5, 7, 3, 4, 0, 6, 1)
i checked around to see if i was being watched but the room was definitely empty and i couldnt hear anything outside so i ducked down to inspect the underside of the table the top was highly polished with a graceful slope to the edge thickening as it approached the centre column there was no visible mechanism to suggest that it was anything more than it appeared to be a grand worktable at the centre of a grand control room i pushed poked and listened for another mechanism but there was nothing mechanical that i could find the thickening of the top and the bulk of the column did allow room for a fairly substantial mechanism though and tucked up in the fold where the top joined the column there was a small metal plate bearing a makers mark my heart skipped the door to the shadow archive carried a similar plate inscribed with the trademark of john tann the locksmith who manufactured the security system on the entrance it looked like he had also made this table he was not a furniture maker and there could only be one reason he had made this one it must be part of a lock mechanism he was the leading safe maker in victorian london and if black had felt the need for him to build a safe in the heart of the shadow archive it could only be because there were secrets that were too dark even for the security of the archive itself maybe this is what my attacker was really after and if so they had struck way too soon i should thank them really without my aching head i would have been unlikely to discover tanns mechanism but that thought reminded me i was still vulnerable down in the shadows i didnt think there was anyone else around but i couldnt be sure and i needed backup until now there hadnt been enough to get harry involved in this adventure i still wasnt certain that he would be allowed to help out as i wasnt really sure that national security was involved but i was absolutely certain he would want to see this i needed to get out safely and come back with a team so we could properly explore the archive and find out what the tann safe stored before i left i took one more look around gathering the few papers that were left and putting the code book securely into a pocket of my backpack i still couldnt believe that my attackers had left it behind but perhaps they missed it in the gloom in their excitement to gather the government papers which they had found if nothing else came out of this i was certain that the code book was worth reading i hadnt had time to inspect it properly but the section on the vigenere cipher looked absolutely fascinating
"""

text = """
WSLLC PZHSG CJWOI PGADM NRTWN VUUGE FHRJI EFNTK SLJHG POPAJ LLBAS ATKSY GUSWO JLPNR DHWJO QTAJL NFSZA ZRDSH AJAXU DLAHH AKGKW LHDZP SSOIH OLHHW FKTKS LWVPO SZGUO WGAWT TROCJ LEWVW LIUOU WJPAQ ZENLS FCQFA FRFHW ZSLBP ZLCDZ YMSUV CBAUT HFJSA IRBWD HFIOE JZIWV EFRSD ZEKIU UMLDH NVHKE VVHVE EVNSS NZHPV PWURT RJEWU NDVAO HSVIY ULSVT QDAHH FAAAI VAKKA UQIOM HLWCD SCEDB JGFEG PKLOS DZEKI UUMWF KGOOZ KAOQS XMAIK ORWZO PSOQT PDHDQ DIWVD AZVLS SKAHH HAJYI EZAWC EQHOL OAWVW NLPUS YAWIW OPWKT KWOUY IVWOU HNQCP TLUQR KFLAQ RPZLR HONWV TKSNU VNVWZ WYAWW KFZRX GOAHN DUCJL SVWKF TUVHO LPLOP AATPH RAVPF ZSWJL TRFAL HIQCQ JPNIZ QWUCH WJLOE USCAV NPMWY LNWGP WSLPS PZHTW VAJBS VWWFL MSSNG YMHHS AAHWV ASBSW FESUS DHXMK ASSOL HTWVA KAAUH KXAHH MASYT RREKJ UVGPZ LIUWJ LLNWW KFZIQ HDWLV HBPGM WDFWF KIWWO JBMRI NWKTK OPLOE BDHSU TRFAK ARXQP MYEWV ATHLN OJKPN DBAXM OUHPG JOQHN GSTKS ODHVL QIGCE VTKJH UQWBA LDVHW LLIWW OEFOZ BRALW WVWLA HHGHS CSPOU TLAPC OLBSH TQDHL OMEFI LRQGA UGWVA WEPDB OAVNL GPEVV HAAFA IQFQK ZIDOJ VPHDJ ASKVL GAVAH HUKNL RQAAF ATRWJ NPTHH DWHUV HNAHN VHKBV IQIOA UMDFY ZAOVS AAMWH QWFLF ISYLH DLDHG TAWWY KVLXH EGUTR IJLHN JZALO IVUKJ KIDBG FVTSS NZHPV KAUHN IWJVZ OPSPZ PNJAK JLAWH NSJTL JAXVR WVAEA HDHSA SLZSW CLNWV AAYDH DAFKE QQAGU TVONS SEAOJ VLRLW EXDEI OEDAH HBEXL AUHDS AMRFA VPRHQ PSJTL CJEHY QSAVA OESPS REQWD SCELB IQWOV GAKZI RBYGW IHGKX JEUHW AULHH PWYSW VWLOA YSXWL NFWNU BLDHE FNIQT NSUZM COWMS FCQJA TKOPA AHLBG EPGKH XWZUI TEUPE QHHQL MEONJ HSVWJ YAOFC JULNW FWLLM LBZKV NWVAS KVDBP SNEVC BOVRN WJYDI WVQKP NVHWT PLLHU AUTKS NWNIR BEKJE UHWAU LBGKE LTKWJ YAOES BWHRH RXMAP HFDSW SZSYS UCRBR AUCHH DWHUV HNAHN VHDSA SWOXA SIWMS GBLGP AOVRV SEXPT LGOWJ UUSZT FTKSN MZSLO JKPFZ SYSUN RHPMY NDIOL YIDHK GBRFO QKLIW AEYOT ESJWJ EVGWJ FTRIJ VLRWO GWHCD ALSPG QHKKA IUILL OEOCY SSPRD QDHTL CJKWE UVWHZ RXGOA HWRIH VAHLB GLDIF SXWMO USCWA TLBCA UVRZR WKIIH DWFWH FAFVT DPHWA OVSYM YEDGP SILHG ALALH AAFAB BTKJJ ERTWJ TSDZK FLTKS HWZSR BOGMT KSYJP MHODS CEQCP TLEQT KJNOW HAFIY DBUGM IWGYG TBDHW FASPC ZWYNZ ONXHR HWOYY OZWJY PNGIO LYIDZ EFPTV GYSSE DBZLO EFCOL ZOIQK FMLLQ PSYES FKZPB LHENL IDAYW YTDWJ LOAWH DWZTR FEWZT RZZTF NLUDL PNJOH WVFWV AZVRU WBAJW RIJVZ SXTBW YEGHD WYEKO RWZOI HAFLD WVASW PHHEL LOIGK ELFRF KHLNF CJXSI FHWFK PHFDS WSWVW LPSUS OHVNV WXDLF RFDWY MDXAK AYVGQ HWOUH KXAHH GDSKO ZONUO IYSWF KAOZE LZWRF GKPMX GPFVT OSPZL RGCSF UOUHD WLMSW NW
""".replace(" ", "").strip().lower()

Utils.get_stats(text)
print(Vigenere.auto_decode(text))

"""
Vigenere key: SHADOW
elliot has done himself no favours in arguing the pragmatic line at the constantinople conference disraeli caught the mood with his pamphlet and the people do not seem to agree that bulgarian lives count for less in the calculus of international affairs i think salisbury plans to move him on perhaps back to vienna he was successful there it is most unusual to have annoyed both salisbury and gladstone but i have some sympathy with his views the terrible events that have precipitated this crisis cannot be undone and there are other considerations russian aggression must still be impeded if we are to retain our influence in the region my agents tell me that the russian emperor met with the austrians at budapest at the start of the year to discuss their intentions in the event of war and it is rumoured that they plan to restructure the balkans in an effort to control the slavic moves for a unified state it is my own view that the slavs may be a most useful ally in blocking the expansionist movement in russia and i have advised the government to invite the austrians to join us in march to see if we can effect a diplomatic solution to untangle this gordian knot perhaps we can find some thing more attractive for them that will weaken their dependence on tsar alexander ii if we fail then i fear that more direct action may need to be taken i have in my possession copies of certain letters that have been circulating in franz josefs court that i think might be sufficiently embarrassing to concentrate minds on the advantages of working with us instability in the region is certainly something to be feared but perhaps we can convince the austrians that stability would be worse if it is secured by the russians if we cannot turn austria to our cause it might be necessary to undertake a campaign to stir up the local populations perhaps russia would think twice before getting involved if they were not able to secure a stable settlement by force of arms alone the lessons of the crimea have not been forgotten by any of its combatants modern warfare is growing industrial in its scale and the costs of conflict are prohibitive i am certain that the stories told by nightingale of the horrific wounds suffered there have softened the appetite of some for open conflict and perhaps that is responsible for her majestys support of the shadow archive and all its works i must not let her down nor the empire
"""