from CipherUtils import *
#
text = """
WFREZOBRHCESTIKVBZEOGOAXZGGHTQFADLGEPBHXDIRSMELEQBGODKAIVRBTTMMEEJRSMNXFXRAEUBAIUMSUEEXVHIREZQVSXJQSQMMLDRVTIWNPGZRWAZMLDJBTFWVSOJRCFWKWDLQPDWUEEJLBQTHRJCQIZIFYVCHMTIKVBQNIPPXEJPREPJNXLFNDMNXIOGAGTMPEQRRDUBBRVRNLXMWFDAXIZPXEGOHADBXVVRUEDMPEVQBMQBAMQECRAXKMHRBRUIEMQRUEIIRLHJBOWMWEWGGIFBHSNRUEFEHSISFEUOAXHCAHACKWWMPRMKDMWZHTIQMLDQDUMLKSQMSSBMVMDJSODKXWIPBMTMKIIMEDSCTVGGAGGAMLHPRWMAGSUGFKFPTXPWNTFIVOHPFWACEHUCGUDVBEVIRDTIKVBFBWTMZSWYHTTWKMVYGIAVMSEPVNSBAIPGAARBXVDJYWQAMMOJJEDMGXVSEEFPTXWFRRQEXVHYAYZIMMRLNLEMVYUGGYUUIPLANTUWGWESGHQRNWWJNUSPXHDLQPAQGXHBBUFBAEWURWQZXGXPEEZBECVMZEIPXVHSADQZGIZQPOFTTRGWNRPIGHLRUAPVMXDIRNYCVLWMPOZDBRFCGHQPHQHQRCDMMEUWGHMBPIQCRDQLTTUMCEDAXGXPVTKBXEPRBGGIKHWFRSTIWSZYECTQOIDLBTTMKXHYZORIGEOWFTEPTHFYZPQLHRRLRSULXSIRUEOWFQDLQCQVMVHYADIMKIFMZBUVZXKPBUSPUPDAXSOWWIEMBKMVWXKCSEIXTTHPFTTIMSXPNNFIZSQGFTEPTHOCSTNMAMQBSRAUMMPCGOFQFIRLRORBAIWPBOBMKWZMHLPIKVLTRWUBAEQMGHQZUSAMSDAKNQHLGSDMMVLCIEPNKSPYFIPMKSRKBRMUHVHBVSFIGXSYETANMLHYECTQOIOYOYDQGXKKBSFKHYOBOEPMVVBNGEPYNMFIYYGABRJRUEEBTRGYEDFWHPVZYAOSAEGSFEPIKEQERORKBTKCESUVVPXBVNSANFVRVTGBBSQYADFZTRVNBSUBBSQYADMTFSVRAOZMHJLRJAEPTVGCETTIGEYGTEZMKILRJAEAESZQVNOMMLHNNPQZLLDBGONMAEQBYEPEBXKANRQIGHWFRSOIGRHPGHQGAEGZEOGOAXZGGHFPXQZYFNFZXEOJLDQABKQCQFAZMLLQFODBHJZMEKMKHYSJRORBBQHQGHQGVEOJRDTIKVBMIEDBHWKMJHUULSPCGHUVZEQBUEDMTHLRAOPLXHWFRNOIFIEYPKFWPSUIBNFPXWDDRAEEXARPXEPEXXDJXEPIUSXRJHMBBLDBYEMZGIGABNOMKRLLTTTMLLDBBWMZVLLTRAZLUPDAXSEMVVHRJODSYSURUESWOIULZEZBAEUPLDULGXJGIEYCVLDUNYNCMMKYQARMXPLLTHQPTHKCNRPAHQHMSTTQLWWMEYNMYSUCNNPIYXHPGHQAXGRLQTUUXLHUNSOIEPHBNWMGAIVCRMQLIEURVCGTTVOWGHACZLWDHLUILOHBUIYEAEWUNSNWMLHPVNSPBQESGHQETWHLWOKQGKECVNSKKCSRVCTMLELBFOYMMLLLTANWNXWFRBMTDEQNEONTXQWFRNYCMXHPRDEBXZHRHRZMKWSMRMTQLXRPLLQALSQFVSFWKCUCCEMBLMWQRLRPTWWMAOAVXPLQGEZABGRSYDZBZIWYAYFPBRJKBRQWNXRDUIYMQGHNGSAUXGRKZEZBTFRSGWAZDMQEOAOSPEUBFTTZHYJFGHQXTTHPFSAQMYULRDYGTXWCATUWGFDAXTABAIVYSEFPXQHAUAZQLQZYFBUOZIUYADTMTZLCETTIGAHURRQCLIGRBAZLAEGZREZMQUXGFIFMECPYQEFPXGRKCOZMGXVQYIPIEQRQGNAQLIOCFSXGHZHPBNQIGSWFRRMVWXKCYOGLVPLAXSUPTHKCNRPEAIQKBVUVZXKCGANTXWHCZEPBHFHRUEDMLYORBFMJKSNCACAOMSRRUCMBVLLLTOZBAIEYERQTLXKYGMMLXMWCIEZPTVGCETAWIIQUUAFTBXWJRNAQLIWFRLAKDXXKOLQZLQDBRWMAAIDTVLKLBWJSVSQLTRGURHMLMSUCFODBMSGPVLXQGKDQZAXTTGFCFSTWEIWMCAEATRHLQOEKHTHGATABAILLGEDQHVLRJAEILAHJYWQPTHWYXEZBAIHDSODBLMWRVNSQGXKCZIPLEIRDNPUTXSILBTQJHSNQNNPXTTHPFWMATWPYYLBQEIRDJHMBESRIRDXQDIHVCLAABZHQGHQATJHUNSDQZKHBGONTHALDJEYIWIDKVSFIDI
""".replace(" ", "").strip()

Utils.get_stats(text)
print(VariantBeaufort.decode(text, "XCNAOSHW".lower()))

"""
Beaufort Variant Cipher: XCNAOSHW
the engineers harry brought with him wanted to take saws and torches to the table safe but neither of us were keen i could see that it would be worth a lot to collectors and probably belonged in a museum harry said he agreed but i had a feeling he wanted it installed back in headquarters there was something proprietorial in the way he looked at it it took the two of us eighteen hours to crack it but with a squadron of special forces from hereford guarding us there was no risk that my attackers would return i asked harry how he got authorisation to bring them in after all we still werent sure that there were any national security implications but he just laughed and pointed out that we were currently somewhere under new scotland yard and it hadnt taken much to convince the home secretary that we needed a proper security team to guard the shadow archive another team of analysts had camped on one side of the command centre and were combing through blacks code book and the few papers that our antagonists had left behind from time to time one of the troopers would arrive with another box of documents retrieved from a side room or a more distant part of the archive labyrinth most could be decrypted quickly using the standard tools black had used a range of ciphers including substitution and transposition and almost none of it was harder than a vigenere it was slow since the papers had to be handled with care and the scanner they had brought with them wasnt really designed for this sort of work a couple of times they called harry over to show him something and he read it nodded then came back to work on the safe as we worked we talked about what i had learned concerning the shadow archive and blacks secret work for the government harry didnt give much away but i had a feeling he had heard some of this story before and after the second time he was called away he seemed particularly thoughtful i asked him what was bothering him but he was enjoying being cryptic he said something about the balkan problem then muttered steve turners poem history lesson history repeats itself has to no one listens i couldnt get anything more out of him except some comment about working backwards through the papers so i turned my attention back to the safe the mechanism was bigger and heavier than we were used to and had been exquisitely made the components slid almost noiselessly over one another and the loud clicks i had heard when moving the table seemed to be the result of a broken cog tooth catching on the barrels that made it even harder to open what little noise the lock tumblers made was heavily disguised and we had to resort to drilling a small access hole to pass an endoscope into the interior it was as well we had taken the effort sitting in the middle of a pile of notebooks and papers was a small pile of what looked like explosives the safe was rigged to blow if we made a mistake
"""

text = """
XLLDY DXLLM IQXLF WHLTQ VXEEG CKKIP VZFOT MAYYD RGFYY DLRBQ PVIQH FTUVM PIKOY LBNEY GJECN SRMBA VBXYA NESHJ HBKYS DTMLO ZGZFC SAYBH JYFLB EIYAR XHKXI ETLLY SQYCP VXLXH RWVCI HFSXQ XOHXE IEUSO LRXFK DIQHN JZEFK YGNRY LHZKK JTCIY XGKLV DRYBM JEVCG CDBIB GOFDI NHBVG IRTNJ XEKHN KYIFM IKUGY UUZXS BXWRW KLBXR BXWUY DSXCF UJOLR MUJOX SHLVN EPMHR ORYKL VDMBX GVRXD HFFBX LHWIE SEGCK XIKXW JEVNR WESEE RUDOA RTBKC VSHGL BHPTY YOZYA CUXEQ XCKSR SMLFZ TMZHZ NEPMH ZRGGK YSVPG PSEKQ PXAES VYTTR LGGMU DYPNB XVRXD HYIOL NLIDD EBXCQ XIPYY YDIQK OFMJM LLVGS NKIAK QCANE YQCAN YQYMK BKBEC UIKOV SLMVB TEGCI LRYVY NDEFM YGYLC ANESC RBFZL ERLHZ NIPNN IERCO UYCRY DFRLI FMMJY VATMK XIETS DCIGM LRZHL TMVDE RLLVV PYFMV RXLHM ZCYAH ZPWXS UQVSZ YXPRR IPNMD KMJEC NCVCP IGBSH TGVRX DHFCK WQXLX XSAXB KPSLK YTXSA XFGSG LBLGO LRLCU OZCBB TKIZM BXSQL HCKKG GYCEE WGANI OLRXB NNRYP IYPSL HCKCI SJYYD IJUCK KTKHW ESIPT YJOLR WHRCA CBPCK ZGKSE KQWKY MOVYX LVRXR TBKBI FMUID YZTYU SVYXF TKOAT FPOLR MUYDX MGMZD MEGCU KIJLC DCMRT BKCTY ALVZR MBNRM MDBHL OLRWU VVHJN IYCCR KUGRG GAQWY ECWCI KIJVI ENRYG QFBMC ANWYW LHCKS FKTFR MMRBF FZHLT FRBYR EOTNI GKUMR XGPXV NMTBX ESEKX LJOZJ XMDOL RLYKK XQGUB VEZXB KXSGM OCYWL TECKF YDYVC SFPYJ YLRWH RKMQL OIXMF MCNOM JWFLY LQKYN YTQMC WYWSV ICOLR MUYDI TXCCO FMAQV CSFMH VOARX VKSPN LSCZI CWMZD YZWYZ PMLNH VOFCO UYIPY MCUXE WGUDB IEMUY DCYPY DKWCA NESWC MUKCG GOUCC IFMYK SRSHN JWMYM HVWIT HGTSZ YEMEK TCANJ SWGKW VRXDH NLYCY PUVOW WTGVG ITXCC OFGGY YDRGE LVLXY TXEOK YXBKV SPMHF MRYVY NPMRV CCPRM VLVRX PNZDY VDXMF VSRXL FWKLB BKOQM LYMKL WXBKD EFMXV CMJTY IOZYA FCKHL TNEOR GMHFM IFMMJ YVATN GEVCR UDBEU MUYDX YXLYD KLBLV RXYZY YDICL IKXYE XVVFE FLLVG SNKIA KQCAN WYPJT MVFMJ GCKCS AKYNY PFVOD KXYWY VMGSL NYQMK RWRWS JICUP SQWIY DIKPY EBYMM UYDWG XJFRC KMMFM XYXLX DELXN WYHLT NYQYM UYIKK LBHES AFMLF GWCBL FDGGO FCKXY ANNOM TRGJS XGMOS DLENI ILRYX GPVIP NMKCY KBNRR XBBUJ NRYXG UOXAX LIYGC ALZKJ WTFGY XQBBK NMYLC EOLUG IZDYJ HMVBE PHZVZ SFHNE SKCUH RMMLB FIOFL BMJOV EGITQ RGWHV ZQGXB KDERA ALYFC UNYQM KXWRO TRTBK DGCIM FBTCA NYDMU RFCKR GYQFX RGANZ GWCBG VXIEG CKRKG YSXBI LXYCL EPXXZ CRMVX VNRCI RVOZY ACUXE JEUYO XGAQE SVYEO GYTWE FRCVC OCEER CXVKY RCOUY CHMAN VWCKL MVVIF MYEYR KXFSY VNAMZ UVSMY YDSRG IZDYJ HMEGS PNIKX IQXLG YXQKY NYTEG CUKIJ KYYDS FMCNO XYBNF QILHN ESKCU IKOPZ TYIOA CPXEY GCLXE KWCBG VXIPN IWYWC VCMBI QVCKK QMEJZ NIFMH ZRXGP EIYAR XHKXI ETLLY TMEYM OHMMY CLECK YNOAR LLZPW EGCYD SUMXV FIGAW RIEJX XJSLR MUYDJ JXMPW XPHZD YGGWH ROPZT NZFIL BYYDC YEYUY XBXEI YAQXC CVECA NXXSK THFSW SYHFM KLBQF CJMRA VDEPM MIESL HCKEP MLFRX SGMUE BIRGC EKSRX FSKRC FUVLS RZHZB ECIJR OPGAQ EYMRB MFZLQ BNZBF CANXX MQBFR XMEKU DIPCO CKMID YYUXE YBLKC YYWHR IRYFL VQRGL YZVPY KYYRX GPHFS XATLF PXPHJ GEWEG CUVMS USCDG CYLVZ HLTBI OLBXS RVTQT BRSWQ NLUOV YXZVG XYANC VELXY SCEFK UNRWG DLLDS QLOIO LR
""".replace(" ", "").strip()
Utils.get_stats(text)

text = text[::-1]
Utils.get_stats(text)

v = Vigenere.auto_decode(text)
print(v[0][::-1], v[1])

"""
Reversed then Vigenere, key: Turkey
the russo turkish war has been all that we feared russia has played her hand perfectly building support for action with her allies in germany and austria and effectively marginalising the british position while appearing to be amenable to an international solution our strategy of sowing confusion among the allies worked to delay the inevitable and i comfort myself that this delay achieved two things first we were able to develop our agent network within the diplomatic services of our enemies and second we were able to begin to negotiate with other leading powers to present our own solution to the turkish problem nonetheless my methods have not been universally popular in whitehall and i have expended considerable energy fighting enemies within now finally with the prospect that peace might be bought at the impending congress in berlin i can begin to hope for a resolution when i said this to playfair he corrected me and said that i must surely mean brought but it is my view that all victories worth winning are bought and often at great cost my hope is that our new methods of diplomacy might succeed at a much lower cost in lives all of the major powers have begun to see the gathering threat that war may erupt across the continent and all have realised that they have something more to lose from further conflict if we can control the agenda at berlin then i believe we may see a way out of the crisis the pan slavic movement aims to unite the slavic states in the same way that germany and italy have been unified but is deeply split between those who believe that the locus of its power should lie within russia and those who seek a balkan solution the balkan states themselves remain divided with varied cultural and political ambitions of their own and no clear idea of which party should lead the unification perhaps that is misleading it is not that they lack a clear idea but rather that there are very many rival views and these are incompatible the question of how and whether this unification might be achieved is the principle concern of the congress all of the major powers will i am sure have a view but my focus is on the smaller states and parties my agents across the balkans have nurtured instability in the hope that we can bring pressure to bear through them on the major powers of course the frenzied atmosphere of the diplomatic bazaar in germany will be rich in trading opportunities and i have heard rumours that we may gain cyprus cementing our control of the mediterranean trade routes at the same time by trading macedonia back to the ottoman state we hope to undermine russian territorial gains and perhaps to settle the balkan question permanently if so our agent network in bosnia will give us a foothold in that region i will continue to work closely with them in the hope of creating a new and more secure future
"""